### ISSUE TITLE
actions: additional lookup path for policy files

### ISSUE THREAD

**Issue by polkit-github-migration-bot** [polkit-org/polkit#130]
In gitlab.freedesktop.org by lucab on Oct 13, 2020, 11:27

Link to the original issue: https://gitlab.freedesktop.org/polkit/polkit/-/issues/129
This is a request for enhancement related to how/where polkit looks up for `actions/*.policy` files, in order to make it easier to split OEM/vendor actions and local-admin configured ones.

On transactional Linux distribution (e.g. those based on [ostree](https://ostreedev.github.io/ostree/), or adopting an A/B partitions update model), most of the `/usr` hierarchy is part of OS-versioned content and is mounted in Read-Only mode. This includes content under `/usr/share/polkit-1/actions` which is thus not editable by a local-admin.

As a user of an atomic Linux distribution (e.g. [Fedora Silverblue](https://silverblue.fedoraproject.org/)), I'd like to able to define my own `.policy` action files somewhere under `/etc/`, so that I can define local policies without modifying OS-owned content.

In particular, it would be good to have a lookup split similar to the one currently existing for rules files (`/usr/share/polkit-1/rules.d/` plus `/etc/polkit-1/rules.d/`, with etc-priority).

**Comment by taukakao** [comment]
This is quite an important issue for me.
Some apps (for example the gnome extension Battery-Health-Charging) need to add policies during runtime and they have to put them into `/usr/share/polkit-1/actions` which is wrong according to the Linux filesystem standard. 
This breaks on immutable distros since /usr is not writeable there.

I don't see a security impact in adding a lookup path in /etc so it would be very appreciated.

**Comment by vmihalko** [comment]
https://github.com/polkit-org/polkit/pull/499 has recently resolved this issue.

**Comment by taukakao** [comment]
Thanks for the info! :)
